export const animals = [
  "Ostrich",
  "Wolf",
  "Silky shark",
  "Great white shark",
  "Sand tiger shark",
  "Hippoglossus",
  "Halibut",
  "Ground beetle",
  "Nile crocodile",
  "Redfish",
];

export const negativeKeywords = [
  "Mobile Case",
  "Tool",
  "Faux leather",
  "Crystal",
  "Print",
  "Appliance",
  "Mask",
  "Artificial",
  "Mock leather",
  "Painting",
  "PU leather",
  "Fake leather",
  "Photograph",
  "Oil Tank",
  "Gem",
  "Vinyl",
  "wooden",
  "Glass",
  "Print",
  "Toy",
  "Pajamas",
  "Custom",
  "Figurine",
  "Plastic",
  "T-shirt",
  "Resin",
  "Photo",
];

export const descriptions = [
  "cobra",
  "cobra taxidermy",
  "cobra scale",
  "cobra skin",
  "cobra skeleton",
  "cobra Carcass",
  "cobra Meat",
  "cobra leather",
  "cobra Trophy",
  "cobra Pelt",
  "cobra Hide",
  "cobra Live",
  "python",
  "python taxidermy",
  "python scale",
  "python skin",
  "python skeleton",
  "python Carcass",
  "python Meat",
  "python leather",
  "python Trophy",
  "python Pelt",
  "python Hide",
  "python Live",
  "boa",
  "boa taxidermy",
  "boa scale",
  "boa skin",
  "boa skeleton",
  "boa Carcass",
  "boa Meat",
  "boa leather",
  "boa Trophy",
  "boa Pelt",
  "boa Hide",
  "boa Live",
  "snake",
  "snake taxidermy",
  "snake scale",
  "snake skin",
  "snake skeleton",
  "snake Carcass",
  "snake Meat",
  "snake leather",
  "snake Trophy",
  "snake Pelt",
  "snake Hide",
  "snake Live",
  "lizard",
  "lizard taxidermy",
  "lizard scale",
  "lizard skin",
  "lizard Claw",
  "lizard Foot",
  "lizard Feet",
  "lizard Bone",
  "lizard skeleton",
  "lizard Carcass",
  "lizard Trophy",
  "lizard Pelt",
  "lizard Hide",
  "lizard Live",
  "varanus",
  "varanus taxidermy",
  "varanus scale",
  "varanus skin",
  "varanus Foot",
  "varanus Feet",
  "varanus Bone",
  "varanus skeleton",
  "varanus Carcass",
  "varanus leather",
  "varanus Trophy",
  "varanus Pelt",
  "varanus Hide",
  "varanus Live",
  "crocodile",
  "crocodile taxidermy",
  "crocodile scale",
  "crocodile skin",
  "crocodile Paw",
  "crocodile Claw",
  "crocodile Foot",
  "crocodile Feet",
  "crocodile Teeth",
  "crocodile Tooth",
  "crocodile Skull",
  "crocodile Bone",
  "crocodile skeleton",
  "crocodile Carcass",
  "crocodile Meat",
  "crocodile egg",
  "crocodile leather",
  "crocodile Trophy",
  "crocodile Pelt",
  "crocodile Hide",
  "crocodile Live",
  "alligator",
  "alligator taxidermy",
  "alligator shell",
  "alligator scale",
  "alligator skin",
  "alligator Paw",
  "alligator Claw",
  "alligator Foot",
  "alligator Feet",
  "alligator Teeth",
  "alligator Tooth",
  "alligator Skull",
  "alligator Bone",
  "alligator skeleton",
  "alligator Carcass",
  "alligator Meat",
  "alligator egg",
  "alligator leather",
  "alligator Trophy",
  "alligator Pelt",
  "alligator Hide",
  "alligator Live",
  "lynx",
  "lynx taxidermy",
  "lynx skin",
  "lynx Fur",
  "lynx hair",
  "lynx Paw",
  "lynx Foot",
  "lynx Feet",
  "lynx Skull",
  "lynx Bone",
  "lynx skeleton",
  "lynx Carcass",
  "lynx Meat",
  "lynx Trophy",
  "lynx Pelt",
  "lynx Hide",
  "lynx Live",
  "monkey",
  "monkey taxidermy",
  "monkey skin",
  "monkey Fur",
  "monkey hair",
  "monkey Paw",
  "monkey Claw",
  "monkey Foot",
  "monkey Feet",
  "monkey Teeth",
  "monkey Tooth",
  "monkey Skull",
  "monkey Bone",
  "monkey skeleton",
  "monkey Carcass",
  "monkey Meat",
  "monkey Trophy",
  "monkey Pelt",
  "monkey Hide",
  "monkey Live",
  "macaque",
  "macaque taxidermy",
  "macaque skin",
  "macaque Fur",
  "macaque Paw",
  "macaque Claw",
  "macaque Foot",
  "macaque Feet",
  "macaque Teeth",
  "macaque Tooth",
  "macaque Skull",
  "macaque Bone",
  "macaque skeleton",
  "macaque Carcass",
  "macaque Meat",
  "macaque leather",
  "macaque Trophy",
  "macaque Pelt",
  "macaque Hide",
  "macaque Live",
  "lemur",
  "lemur taxidermy",
  "lemur skin",
  "lemur Fur",
  "lemur hair",
  "lemur Paw",
  "lemur Claw",
  "lemur Foot",
  "lemur Feet",
  "lemur Teeth",
  "lemur Tooth",
  "lemur Skull",
  "lemur Bone",
  "lemur skeleton",
  "lemur Carcass",
  "lemur Meat",
  "lemur Trophy",
  "lemur Pelt",
  "lemur Hide",
  "lemur Live",
  "chimpanzee",
  "chimpanzee taxidermy",
  "chimpanzee skin",
  "chimpanzee Fur",
  "chimpanzee hair",
  "chimpanzee Paw",
  "chimpanzee Claw",
  "chimpanzee Foot",
  "chimpanzee Feet",
  "chimpanzee Teeth",
  "chimpanzee Tooth",
  "chimpanzee Skull",
  "chimpanzee Bone",
  "chimpanzee skeleton",
  "chimpanzee Carcass",
  "chimpanzee Meat",
  "chimpanzee Trophy",
  "chimpanzee Pelt",
  "chimpanzee Hide",
  "chimpanzee Live",
  "gorilla",
  "gorilla taxidermy",
  "gorilla skin",
  "gorilla Fur",
  "gorilla hair",
  "gorilla Paw",
  "gorilla Foot",
  "gorilla Feet",
  "gorilla Teeth",
  "gorilla Tooth",
  "gorilla Skull",
  "gorilla Bone",
  "gorilla skeleton",
  "gorilla Carcass",
  "gorilla Meat",
  "gorilla Trophy",
  "gorilla Pelt",
  "gorilla Hide",
  "gorilla Live",
  "otter",
  "otter taxidermy",
  "otter skin",
  "otter Fur",
  "otter hair",
  "otter Paw",
  "otter Claw",
  "otter Foot",
  "otter Feet",
  "otter Teeth",
  "otter Tooth",
  "otter Skull",
  "otter Bone",
  "otter skeleton",
  "otter Carcass",
  "otter Meat",
  "otter Trophy",
  "otter Pelt",
  "otter Hide",
  "otter Live",
  "turtle",
  "turtle taxidermy",
  "turtle shell",
  "turtle scale",
  "turtle skin",
  "turtle Paw",
  "turtle Claw",
  "turtle Foot",
  "turtle Feet",
  "turtle Skull",
  "turtle Bone",
  "turtle skeleton",
  "turtle Carcass",
  "turtle Meat",
  "turtle egg",
  "turtle Trophy",
  "turtle Live",
  "tortoise",
  "tortoise taxidermy",
  "tortoise shell",
  "tortoise scale",
  "tortoise skin",
  "tortoise Paw",
  "tortoise Claw",
  "tortoise Foot",
  "tortoise Feet",
  "tortoise Skull",
  "tortoise Bone",
  "tortoise skeleton",
  "tortoise Carcass",
  "tortoise Meat",
  "tortoise egg",
  "tortoise Trophy",
  "tortoise Live",
  "owl",
  "owl taxidermy",
  "owl Fur",
  "owl Claw",
  "owl Foot",
  "owl Feet",
  "owl Skull",
  "owl Bone",
  "owl skeleton",
  "owl Carcass",
  "owl Meat",
  "owl Feather",
  "owl egg",
  "owl Trophy",
  "owl Live",
  "shark",
  "shark taxidermy",
  "shark scale",
  "shark skin",
  "shark Teeth",
  "shark Tooth",
  "shark Skull",
  "shark Bone",
  "shark skeleton",
  "shark Carcass",
  "shark Meat",
  "shark egg",
  "shark leather",
  "shark Trophy",
  "shark Oil",
  "shark Bile",
  "shark Pelt",
  "shark Hide",
  "shark Live",
  "birds of prey",
  "birds of prey taxidermy",
  "birds of prey Fur",
  "birds of prey Claw",
  "birds of prey Foot",
  "birds of prey Feet",
  "birds of prey Teeth",
  "birds of prey Tooth",
  "birds of prey Skull",
  "birds of prey Bone",
  "birds of prey skeleton",
  "birds of prey Carcass",
  "birds of prey Meat",
  "birds of prey Feather",
  "birds of prey egg",
  "birds of prey Trophy",
  "birds of prey Live",
  "falcon",
  "falcon taxidermy",
  "falcon Fur",
  "falcon Claw",
  "falcon Foot",
  "falcon Feet",
  "falcon Skull",
  "falcon Bone",
  "falcon skeleton",
  "falcon Carcass",
  "falcon Meat",
  "falcon Feather",
  "falcon egg",
  "falcon Trophy",
  "falcon Live",
  "eagle",
  "eagle taxidermy",
  "eagle Fur",
  "eagle Claw",
  "eagle Foot",
  "eagle Feet",
  "eagle Skull",
  "eagle Bone",
  "eagle skeleton",
  "eagle Carcass",
  "eagle Meat",
  "eagle Feather",
  "eagle egg",
  "eagle Trophy",
  "eagle Live",
  "goshawk",
  "goshawk taxidermy",
  "goshawk Fur",
  "goshawk Claw",
  "goshawk Foot",
  "goshawk Feet",
  "goshawk Skull",
  "goshawk Bone",
  "goshawk skeleton",
  "goshawk Carcass",
  "goshawk Meat",
  "goshawk Feather",
  "goshawk egg",
  "goshawk Trophy",
  "goshawk Live",
  "sparrowhawk",
  "sparrowhawk taxidermy",
  "sparrowhawk Fur",
  "sparrowhawk Claw",
  "sparrowhawk Foot",
  "sparrowhawk Feet",
  "sparrowhawk Skull",
  "sparrowhawk Bone",
  "sparrowhawk skeleton",
  "sparrowhawk Carcass",
  "sparrowhawk Meat",
  "sparrowhawk Feather",
  "sparrowhawk egg",
  "sparrowhawk Trophy",
  "sparrowhawk Live",
  "Primate",
  "Primate taxidermy",
  "Primate skin",
  "Primate Fur",
  "Primate hair",
  "Primate Paw",
  "Primate Foot",
  "Primate Feet",
  "Primate Teeth",
  "Primate Tooth",
  "Primate Skull",
  "Primate Bone",
  "Primate skeleton",
  "Primate Carcass",
  "Primate Meat",
  "Primate Trophy",
  "Primate Pelt",
  "Primate Hide",
  "Primate Live",
  "Bird",
  "Bird taxidermy",
  "Bird Fur",
  "Bird Claw",
  "Bird Foot",
  "Bird Feet",
  "Bird Skull",
  "Bird Bone",
  "Bird skeleton",
  "Bird Carcass",
  "Bird Meat",
  "Bird Feather",
  "Bird egg",
  "Bird Trophy",
  "Bird Live",
  "Reptile",
  "Reptile taxidermy",
  "Reptile shell",
  "Reptile scale",
  "Reptile skin",
  "Reptile Paw",
  "Reptile Claw",
  "Reptile Foot",
  "Reptile Feet",
  "Reptile Teeth",
  "Reptile Tooth",
  "Reptile Skull",
  "Reptile Bone",
  "Reptile skeleton",
  "Reptile Carcass",
  "Reptile leather",
  "Reptile Trophy",
  "Reptile Oil",
  "Reptile Bile",
  "Reptile leather",
  "Reptile Pelt",
  "Reptile Hide",
  "Reptile Live",
  "Lion",
  "Lion taxidermy",
  "Lion skin",
  "Lion Fur",
  "Lion hair",
  "Lion Paw",
  "Lion Foot",
  "Lion Feet",
  "Lion Teeth",
  "Lion Tooth",
  "Lion Skull",
  "Lion Bone",
  "Lion skeleton",
  "Lion Carcass",
  "Lion Meat",
  "Lion leather",
  "Lion Trophy",
  "Lion Pelt",
  "Lion Hide",
  "Lion Live",
  "Cheetah",
  "Cheetah taxidermy",
  "Cheetah skin",
  "Cheetah Fur",
  "Cheetah hair",
  "Cheetah Paw",
  "Cheetah Foot",
  "Cheetah Feet",
  "Cheetah Teeth",
  "Cheetah Tooth",
  "Cheetah Skull",
  "Cheetah Bone",
  "Cheetah skeleton",
  "Cheetah Carcass",
  "Cheetah Meat",
  "Cheetah leather",
  "Cheetah Trophy",
  "Cheetah Pelt",
  "Cheetah Hide",
  "Cheetah Live",
  "Leopard",
  "Leopard taxidermy",
  "Leopard skin",
  "Leopard Fur",
  "Leopard hair",
  "Leopard Paw",
  "Leopard Foot",
  "Leopard Feet",
  "Leopard Teeth",
  "Leopard Tooth",
  "Leopard Skull",
  "Leopard Bone",
  "Leopard skeleton",
  "Leopard Carcass",
  "Leopard Meat",
  "Leopard leather",
  "Leopard Trophy",
  "Leopard Pelt",
  "Leopard Hide",
  "Leopard Live",
  "Tiger",
  "Tiger taxidermy",
  "Tiger skin",
  "Tiger Fur",
  "Tiger hair",
  "Tiger Paw",
  "Tiger Foot",
  "Tiger Feet",
  "Tiger Teeth",
  "Tiger Tooth",
  "Tiger Skull",
  "Tiger Bone",
  "Tiger skeleton",
  "Tiger Carcass",
  "Tiger Meat",
  "Tiger leather",
  "Tiger Trophy",
  "Tiger Pelt",
  "Tiger Hide",
  "Tiger Live",
  "Ocelot",
  "Ocelot taxidermy",
  "Ocelot skin",
  "Ocelot Fur",
  "Ocelot hair",
  "Ocelot Paw",
  "Ocelot Foot",
  "Ocelot Feet",
  "Ocelot Teeth",
  "Ocelot Tooth",
  "Ocelot Skull",
  "Ocelot Bone",
  "Ocelot skeleton",
  "Ocelot Carcass",
  "Ocelot Meat",
  "Ocelot leather",
  "Ocelot Trophy",
  "Ocelot Pelt",
  "Ocelot Hide",
  "Ocelot Live",
  "Bear",
  "Bear taxidermy",
  "Bear skin",
  "Bear Fur",
  "Bear hair",
  "Bear Paw",
  "Bear Claw",
  "Bear Foot",
  "Bear Feet",
  "Bear Teeth",
  "Bear Tooth",
  "Bear Skull",
  "Bear Bone",
  "Bear skeleton",
  "Bear Carcass",
  "Bear Meat",
  "Bear leather",
  "Bear Trophy",
  "Bear Pelt",
  "Bear Hide",
  "Bear Live",
  "Elephant",
  "Elephant taxidermy",
  "Elephant skin",
  "Elephant hair",
  "Elephant Tusk",
  "Elephant Paw",
  "Elephant Foot",
  "Elephant Feet",
  "Elephant Teeth",
  "Elephant Tooth",
  "Elephant Tusk",
  "Elephant Horn",
  "Elephant Skull",
  "Elephant Bone",
  "Elephant skeleton",
  "Elephant Carcass",
  "Elephant Meat",
  "Elephant leather",
  "Elephant Trophy",
  "Elephant Pelt",
  "Elephant Hide",
  "Elephant Live",
  "Rhinoceros",
  "Rhinoceros taxidermy",
  "Rhinoceros skin",
  "Rhinoceros Tusk",
  "Rhinoceros Foot",
  "Rhinoceros Feet",
  "Rhinoceros Teeth",
  "Rhinoceros Tooth",
  "Rhinoceros Tusk",
  "Rhinoceros Horn",
  "Rhinoceros Skull",
  "Rhinoceros Bone",
  "Rhinoceros skeleton",
  "Rhinoceros Carcass",
  "Rhinoceros Meat",
  "Rhinoceros leather",
  "Rhinoceros Trophy",
  "Rhinoceros Pelt",
  "Rhinoceros Hide",
  "Rhinoceros Live",
  "parrot",
  "parrot taxidermy",
  "parrot Fur",
  "parrot Claw",
  "parrot Foot",
  "parrot Feet",
  "parrot Skull",
  "parrot Bone",
  "parrot skeleton",
  "parrot Carcass",
  "parrot Meat",
  "parrot Feather",
  "parrot egg",
  "parrot Trophy",
  "parrot Live",
  "macaw",
  "macaw taxidermy",
  "macaw Fur",
  "macaw Claw",
  "macaw Foot",
  "macaw Feet",
  "macaw Skull",
  "macaw Bone",
  "macaw skeleton",
  "macaw Carcass",
  "macaw Meat",
  "macaw Feather",
  "macaw egg",
  "macaw Trophy",
  "macaw Live",
  "pangolin",
  "pangolin taxidermy",
  "pangolin shell",
  "pangolin scale",
  "pangolin skin",
  "pangolin Paw",
  "pangolin Claw",
  "pangolin Foot",
  "pangolin Feet",
  "pangolin Teeth",
  "pangolin Tooth",
  "pangolin Skull",
  "pangolin Bone",
  "pangolin skeleton",
  "pangolin Carcass",
  "pangolin Meat",
  "pangolin leather",
  "pangolin Trophy",
  "pangolin Pelt",
  "pangolin Hide",
  "pangolin Live",
  "clam",
  "clam taxidermy",
  "clam shell",
  "clam scale",
  "clam Carcass",
  "clam Meat",
  "clam Trophy",
  "clam Oil",
  "clam Live",
  "taxidermy",
  "shell",
  "scale",
  "skin",
  "Fur",
  "hair",
  "Tusk",
  "Paw",
  "Claw",
  "Foot",
  "Feet",
  "Teeth",
  "Tooth",
  "Tusk",
  "Horn",
  "Skull",
  "Bone",
  "skeleton",
  "Carcass",
  "Meat",
  "Feather",
  "egg",
  "leather",
  "Trophy",
  "Oil",
  "Bile",
  "Pelt",
  "Hide",
  "Live",
  "pet cobra",
  "pet python",
  "pet boa",
  "pet snake",
  "pet lizard",
  "pet varanus",
  "pet crocodile",
  "pet alligator",
  "pet lynx",
  "pet monkey",
  "pet macaque",
  "pet lemur",
  "pet chimpanzee",
  "pet gorilla",
  "pet otter",
  "pet turtle",
  "pet tortoise",
  "pet owl",
  "pet shark",
  "pet birds of prey",
  "pet falcon",
  "pet eagle",
  "pet goshawk",
  "pet sparrowhawk",
  "pet Primate",
  "pet monkey",
  "pet Bird",
  "pet Reptile",
  "pet Lion",
  "pet Cheetah",
  "pet Leopard",
  "pet Tiger",
  "pet Ocelot",
  "pet Bear",
  "pet Elephant",
  "pet Rhinoceros",
  "pet Shark",
  "pet parrot",
  "pet macaw",
  "pet pangolin",
  "pet clam",
  "IVY",
  "ivory",
  "faux ivory",
  "fake ivory",
  "ivorine",
  "ivory colored",
  "netsuke",
  "Chinese bone",
  "Faux ivorine",
  "Carved bone",
  "Antique Chinese ivory",
  "Cow bone",
  "Ivory coloured",
  "Antique Chinese bone",
  "IVY",
  "Chinese carved faux bone",
  "Netsuke",
  "Chinese carved faux ivory",
  "Natural grain",
  "Chinese carved ivory coloured",
  "Natural material",
  "Chinese faux ivory",
  "Okimono",
  "Cross-hatch graining",
  "Ox bone",
  "Cross-hatch",
  "Patina",
  "Carved ivory coloured",
  "Schreger Lines",
  "Deep carving",
  "Faux",
  "Faux bone",
  "bovine bone",
  "Shatoosh",
  "Caviar",
  "Scrimshaw",
  "excotic pet",
  "cites",
  "wildlife",
];
